[package]
name = "lnrod"
version = "0.1.0"
authors = [
    "Dev Random",
    "Valentine Wallace <vwallace@protonmail.com>",
    "Ken Sedgwick <ken@bonsai.com>",
]
license = "MIT OR Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
bugs = ["bugsalot"]

[dependencies]
bugsalot = { version = "0.2", optional = true }

anyhow = "1.0"
base64 = "0.13.0"
bitcoin = "0.26"
bitcoin-bech32 = "0.7"
bech32 = "0.7"
hex = "0.3"
lightning-block-sync = { git = "https://github.com/rust-bitcoin/rust-lightning", features = ["rpc-client"], rev = "ee29bc4096897e5309a95927a287f183db300e8d" }
lightning-invoice = { git = "https://github.com/rust-bitcoin/rust-lightning", rev = "ee29bc4096897e5309a95927a287f183db300e8d" }
lightning-persister = { git = "https://github.com/rust-bitcoin/rust-lightning", rev = "ee29bc4096897e5309a95927a287f183db300e8d" }
once_cell = "1.7.2"
time = "0.2"
rand = "0.4"
serde_json = { version = "1.0" }
tokio = { version = "1.0", features = [ "io-util", "macros", "rt", "rt-multi-thread", "sync", "net", "time" ] }
hyper = "=0.14.4"  # 0.14.5 depends on socket2 0.4 which requires a higher MSRV
prost = "0.7"
tonic = "0.4"
clap = "3.0.0-beta.2"
toml = "0.5.8"
url = "2.2"

jsonrpc-async = "2.0.1"
serde = { version = "1.0.105", features = ["derive"] }


[dependencies.lightning]
git = "https://github.com/rust-bitcoin/rust-lightning.git"
rev = "ee29bc4096897e5309a95927a287f183db300e8d"
features = ["allow_wallclock_use"]

[dependencies.lightning-signer-core]
git = "https://gitlab.com/lightning-signer/rust-lightning-signer.git"
rev = "5dbace7e64b8d0e3770519b4192beaa3df5bb03e"
#path = "../rust-lightning-signer/lightning-signer-core"

[dependencies.lightning-signer-server]
git = "https://gitlab.com/lightning-signer/rust-lightning-signer.git"
rev = "5dbace7e64b8d0e3770519b4192beaa3df5bb03e"
#path = "../rust-lightning-signer/lightning-signer-server"

[build-dependencies]
tonic-build = "0.4"

[[bin]]
name = "lnrod"
path = "src/main_server.rs"

[[bin]]
name = "lnrcli"
path = "src/main_cli.rs"
