[package]
name = "lnrod"
version = "0.1.0"
authors = [
    "Dev Random",
    "Valentine Wallace <vwallace@protonmail.com>",
    "Ken Sedgwick <ken@bonsai.com>",
]
license = "MIT OR Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
bugs = ["bugsalot"]
default = ["tor"]
tor = ["torut", "tokio-socks", "regex"]

[dependencies]
bugsalot = { version = "0.2", optional = true }

anyhow = "1.0"
base64 = "0.13.0"
bitcoin = "0.27"
bitcoin-bech32 = "0.7"
bech32 = "0.7"
hex = "0.3"
futures = "0.3"

lightning-block-sync = { git = "https://github.com/rust-bitcoin/rust-lightning", features = ["rpc-client"], rev = "2b78957888b86760bb16325a23302d9c979b5602" }
lightning-invoice = { git = "https://github.com/rust-bitcoin/rust-lightning", rev = "2b78957888b86760bb16325a23302d9c979b5602" }
lightning-persister = { git = "https://github.com/rust-bitcoin/rust-lightning", rev = "2b78957888b86760bb16325a23302d9c979b5602" }
lightning-background-processor = { git = "https://github.com/rust-bitcoin/rust-lightning", rev = "2b78957888b86760bb16325a23302d9c979b5602" }
lightning-net-tokio = { git = "https://github.com/rust-bitcoin/rust-lightning", rev = "2b78957888b86760bb16325a23302d9c979b5602" }
log = { version="0.4.14", features = [ "std" ] }
once_cell = "1.7.2"
time = "0.2"
rand = "0.4"
serde_json = { version = "1.0" }
tokio = { version = "1.0", features = [ "io-util", "macros", "rt", "rt-multi-thread", "sync", "net", "time" ] }
hyper = "=0.14.4"  # 0.14.5 depends on socket2 0.4 which requires a higher MSRV
prost = "0.7"
tonic = "0.4"
clap = "3.0.0-beta.2"
toml = "0.5.8"
url = "2.2"

jsonrpc-async = "2.0.1"
serde = { version = "1.0.105", features = ["derive"] }
torut = { version = "0.2.1", optional = true, default-features = false, features = ["control", "v3"] }
tokio-socks = { version = "0.5.1", optional = true }
regex = { version = "1.5.4", optional = true }

[dependencies.lightning-signer-core]
git = "https://gitlab.com/lightning-signer/rust-lightning-signer.git"
rev = "dad9ffd05e5bfff416b4ce02db4c41d9531f9f81"
#path = "../rust-lightning-signer/lightning-signer-core"

[dependencies.lightning-signer-server]
git = "https://gitlab.com/lightning-signer/rust-lightning-signer.git"
rev = "dad9ffd05e5bfff416b4ce02db4c41d9531f9f81"
#path = "../rust-lightning-signer/lightning-signer-server"

[build-dependencies]
tonic-build = "0.4"

[[bin]]
name = "lnrod"
path = "src/main_server.rs"

[[bin]]
name = "lnrcli"
path = "src/main_cli.rs"

[[bin]]
name = "test_onion_server"
path = "src/main_test_onion_server.rs"
